"""Patient-key training ancestry for E23/E25 and the fixed MR comparator."""
from pathlib import Path
import json,pickle,re,hashlib,ast
from collections import Counter
P=Path(__file__).resolve().parents[2];V=P.parent;D=V/'data_topaneu26';R=P/'artifacts/research_audit_20260909';O=P/'artifacts/astra6_e23_MR_oof_candidates_20260909'
def read(p):return json.loads(p.read_text())
def group(c):return re.sub(r'(_(?:mr|ct)_\d+)_\d+$',r'\1',c)
def recs(p):return [json.loads(s) for s in p.read_text().splitlines()]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 R.mkdir(exist_ok=True);planning=read(R/'PLANNING_PROVENANCE_AUDIT.json');planning_sets={m:set(v['planning_cases']) for m,v in planning['modalities'].items()};osplit=read(O/'source_split.json');folds=osplit['folds'];owner={c:f for f,s in enumerate(folds) for c in s['val']};dev=set(read(P/'artifacts/astra6_e12_MR_expanded_fp_filter_20260909/source_split.json')['development_cases']);oldpath=V/'nndet_models/Task030FG_TopAneuMR/RetinaUNetV001_D3V001_3d/fold1/splits.pkl'
 with oldpath.open('rb') as f:old=pickle.load(f)
 log=oldpath.with_name('train.log');q=log.read_text().split('TRAINING KEYS:',1)[1];start=q.index('[');actual=set(ast.literal_eval(q[start:q.index(']',start)+1]));old_train=set(map(str,old[1]['train']));assert actual==old_train;ctpath=V/'nndet_models/Task031FG_TopAneuCT/RetinaUNetV001_D3V001_3d/fold2/splits.pkl';ctsplit=pickle.loads(ctpath.read_bytes())[2];ctsets={'deployed_D':set(map(str,ctsplit['train'])),'deployed_S':{r['case_id'] for r in recs(P/'artifacts/astra6_e16_CT_expanded_segmentation_20260909/features/train_records.jsonl')},'deployed_C':{r['case_id'] for r in recs(P/'artifacts/astra6_e09_CT_expanded_location_20260909/features/train_records.jsonl')},'deployed_F11':{r['case_id'] for r in recs(P/'artifacts/astra6_e11_CT_expanded_fp_filter_20260909/features/records.jsonl')},'deployed_F13':{r['case_id'] for r in recs(P/'artifacts/astra6_e13_CT_anatomical_fp_filter_20260909/features/records.jsonl')}};old_val=set(map(str,old[1]['val']));sourceS=recs(P/'artifacts/astra6_e16_CT_expanded_segmentation_20260909/features/train_records.jsonl');S17=recs(P/'artifacts/astra6_e17_MR_detector_crop_segmentation_20260909/features/train_records.jsonl');C02=recs(P/'artifacts/astra6_e02_multiscale_vessel_signature_20260908T173916Z/features/train_records.jsonl');F14=recs(P/'artifacts/astra6_e12_MR_expanded_fp_filter_20260909/features/records.jsonl');sets={'deployed_D':old_train,'deployed_S':{r['case_id'] for r in S17},'deployed_C':{r['case_id'] for r in C02},'deployed_F14':{r['case_id'] for r in F14}};mr40=set(osplit['comparison_excluded']);ct5=set(read(P/'artifacts/astra6_e16_CT_expanded_segmentation_20260909/source_split.json')['fixed_CT5']);rows=[]
 helper_sets={f:{r['case_id'] for r in sourceS if '_ct_' in r['case_id'] or r['case_id'] in set(folds[f]['train'])} for f in [0,1]};helper_actual={f:read(O/f'segmenters/fold{f}/source_split.json') if (O/f'segmenters/fold{f}/source_split.json').exists() else None for f in [0,1]}
 for path in sorted((D/'images').glob('*_0000.nii.gz')):
  c=path.name.removesuffix('_0000.nii.gz');f=owner.get(c);row={'case_id':c,'available_patient_key':group(c),'modality':'MR' if '_mr_' in c else 'CT','role':'MR40_repeated_development' if c in mr40 else ('CT5_repeated_development' if c in ct5 else 'source'),'OOF_owner':f,'TA36_training_exposure':'unknown_historical_patient_list_unavailable','TA36_used_in_E25_F_features':False,'other_learned_models_in_E25_F_features':'none: image normalization, crops and geometric prior are deterministic'}
  for key,cases in (sets if row['modality']=='MR' else ctsets).items():
   row[key+'_has_training_rows_or_membership']=c in cases;row[key+'_has_training_patient_key_member']=group(c) in {group(x) for x in cases}
  if f is not None:
   ds=set(folds[f]['train']);ss={r['case_id'] for r in sourceS if '_ct_' in r['case_id'] or r['case_id'] in ds};assert group(c) not in {group(x) for x in ds|ss};row.update(candidate_D_training_membership=False,predicted_shape_S_training_membership=False,OOF_S_eligible_training_cases=len(ss),E25_development_role=('selection_and_threshold_calibration' if c in dev else 'fit') if f==0 else 'excluded_from_development_fit_and_selection',E25_final_fit_eligible=True,OOF_checkpoint_verified=(O/f'checkpoints/fold{f}_OOF_COMPLETE.json').exists())
   lock=O/f'segmenters/fold{f}/source_split.json'
   if lock.exists():assert set(read(lock)['training_cases'])==ss
  else:row.update(E25_development_role='not_used',E25_final_fit_eligible=False)
  row['cross_pipeline_training_membership']={'MR_S17_has_training_rows':c in sets['deployed_S'],'MR_S17_has_training_patient_key_member':group(c) in {group(x) for x in sets['deployed_S']},'E23_D':{str(k):{'case_in_training_split':c in folds[k]['train'],'training_complete':(O/f'checkpoints/fold{k}_TRAINED.json').exists()} for k in [0,1]},'E23_S':{str(k):{'case_in_eligible_training_rows':c in helper_sets[k],'actual_case_in_training_split':c in helper_actual[k]['training_cases'] if helper_actual[k] is not None else None,'training_complete':(O/f'segmenters/fold{k}/model/LOCKED.json').exists()} for k in [0,1]}}
  row['supervised_planning_exposure']={'deployed_detector_GT_anchor_planning_case':c in planning_sets[row['modality']],'deployed_CT_global_GT_intensity_statistics_case':row['modality']=='CT' and c in planning_sets['CT'],'E23_legacy_MR_anchor_planning_case':c in planning_sets['MR'],'whole_pipeline_independence_established':False,'evidence':'PLANNING_PROVENANCE_AUDIT.json'}
  rows.append(row)
 assert len(rows)==416 and len(owner)==267 and len(mr40)==40 and len(ct5)==5
 for c in mr40:assert all(c not in v for v in sets.values()),c
 for c in ct5:assert all(c not in v for v in ctsets.values()),c
 for f,s in enumerate(folds):assert not {group(c) for c in s['train']}&{group(c) for c in s['val']}
 # Development F fit and selection cases share a fixed D0/S0, both trained on
 # the complementary MR half. Final F then uses both OOF halves; its inputs
 # are per-case held out, but whole-bank mutual independence is not claimed.
 fdevtrain={c for c in folds[0]['val'] if c not in dev};fdevval=set(folds[0]['val'])&dev;assert not {group(c) for c in fdevtrain}&{group(c) for c in fdevval};assert not (fdevtrain|fdevval)&set(folds[0]['train'])
 fcases={r['case_id'] for r in F14};summary={'total_cases':416,'MR40':40,'CT5':5,'E23_source267':267,'E25_development_eligible_cases':{'fit':len(fdevtrain),'selection_calibration':len(fdevval),'fold1_excluded':len(folds[1]['val'])},'actual_rows_pending_candidate_generation':True,'old_D_fold1_train_cases_verified_in_training_log':len(old_train),'old_D_historical_case_not_in_current_source':sorted(old_train-set(owner)),'CT_D_fold2_train_cases':len(ctsets['deployed_D']),'old_D_fold1_val_cases':len(old_val),'E14_training_cases_with_candidate_rows':len(fcases),'E14_training_cases_seen_by_candidate_D':len(fcases&old_train),'E14_training_cases_not_seen_by_candidate_D':sorted(fcases-old_train),'E14_source_selection_cases_seen_by_D':len(dev&old_train),'lineage_by_case_file':'CASE_LINEAGE.json','E23_purpose':'Training-data generation only; deployment D remains MRfold1epoch60 for firstE25 comparison','source_to_deployment_shift_not_removed':'OOF D trained on half the MR source; deployed D on268 historical cases (training-log verified, including since-discardedMR150);264 is F candidate-bearing case count, not detector training count. OOF S helper is GT-bank-only and case-disjoint; deployed S17 also trained with detector crops. Helper source bank includes104CT cases while deployed S17 uses62CT cases; MR amount and CT center/modality proportions differ. Different data amounts/weights remain.','selection_limits':['OOF helper architecture and fixed13epoch duration reuse prior source-research choices; they are not independently nested-selected within each OOF training fold. Own-case weight fitting exclusion is not full research-procedure independence.','F epoch selection and threshold calibration share the same small source-development cases; neither is an independent acceptance set.','MR40 is repeatedly examined external-center development, not a fresh blind test. CT5 is too small for stable conclusions.','Final F uses both crossfit halves; each case is excluded from its own D/S, but feature-producing models can have seen other final-fit cases. No joint-independence claim.','Known supervised planning exposure: legacy MR/CT anchors use all historical GT boxes, including MR40/CT5; CT normalization additionally uses global GT-foreground statistics. E23 reuses this MR plan. Weight-fitting exclusion is not full-pipeline independence; see PLANNING_PROVENANCE_AUDIT.json.','TA36 historical case list unavailable; E25 F features do not use it, but complete C-based pipeline does.','Official case IDs and suffix grouping are available patient linkage; undocumented cross-ID patient identity cannot be ruled out.'],'hashes':{'E23_split':sha(O/'source_split.json'),'old_D_split':sha(oldpath),'old_D_training_log':sha(log),'CT_D_split':sha(ctpath)}}
 summary['known_planning_exposure']={'audit_sha256':sha(R/'PLANNING_PROVENANCE_AUDIT.json'),'MR40_GT_boxes_retained_in_anchor_optimization':58,'CT5_GT_boxes_retained_in_anchor_optimization':5,'CT_global_GT_foreground_normalization':True,'interpretation':'Shared legacy supervised-plan developmental comparison; no whole-pipeline independent-generalization claim.'}
 summary['segmentation_training_case_composition']={'MR_S17':dict(Counter(c.split('_')[1]+'_'+c.split('_')[2] for c in sets['deployed_S'])),'E23_helpers_eligible':{str(k):dict(Counter(c.split('_')[1]+'_'+c.split('_')[2] for c in helper_sets[k])) for k in [0,1]}}
 summary['CT_D_validation_cases_with_training_patient_key_sibling']=sorted(c for c in map(str,ctsplit['val']) if group(c) in {group(x) for x in ctsets['deployed_D']})
 fpath=P/'artifacts/astra6_e25_oof_shape_fp_filter_20260909'
 if (fpath/'features/READY.json').exists():
  frecords=recs(fpath/'features/records.jsonl');fsplit=read(fpath/'source_split.json');counts={role:Counter(frecords[i]['case_id'] for i in fsplit[key]) for role,key in [('fit','training_rows'),('selection','development_rows'),('final','final_rows')]}
  assert not set(counts['fit'])&set(counts['selection'])
  for row in rows:
   row['E25_actual_rows']={k:v[row['case_id']] for k,v in counts.items()}
   if row['E25_final_fit_eligible']:
    prov=read(fpath/f"features/cases/{row['case_id']}.provenance.json");assert prov['own_case_excluded_from_D_and_S_by_group'];row['E25_input_provenance']=prov
  summary['actual_rows_pending_candidate_generation']=False
  summary['E25_actual_cases_with_rows']={k:len(v) for k,v in counts.items()};summary['E25_actual_row_counts']={k:sum(v.values()) for k,v in counts.items()};summary['hashes']['E25_source_split']=sha(fpath/'source_split.json');summary['hashes']['E25_features_READY']=sha(fpath/'features/READY.json')
 cpath=P/'artifacts/astra6_e28_joint_anatomy_location_20260909'
 if (cpath/'features/READY.json').exists():
  cr=recs(cpath/'features/records.jsonl');cs=read(cpath/'source_split.json');ccounts={'classification_fit':Counter(cr[i]['case_id'] for i in cs['train_rows'] if cr[i]['class']>0),'anatomy_fit':Counter(cr[i]['case_id'] for i in cs['train_rows']),'selection':Counter(cr[i]['case_id'] for i in cs['validation_rows']),'final':Counter(cr[i]['case_id'] for i in cs['final_rows'])}
  assert not set(ccounts['anatomy_fit'])&set(cs['development_cases'])
  for row in rows:row['E28_actual_rows']={k:v[row['case_id']] for k,v in ccounts.items()}
  summary['E28_actual_cases_with_rows']={k:len(v) for k,v in ccounts.items()};summary['E28_candidate_origins']=dict(Counter(r['kind'] for r in cr));summary['E28_GT_crop_disclosure']='GT-centered/jittered crops are supervised training examples only; they are not detector-generated OOF proposals. Development selection uses one actual OOF operating box per GT component. Shape helper excludes own-case group for both origins. Organizer vessel masks are predicted silver supervision, not inference inputs.';summary['hashes']['E28_source_split']=sha(cpath/'source_split.json')
 (R/'CASE_LINEAGE.json').write_text(json.dumps(rows,indent=2)+'\n');(R/'LINEAGE_SUMMARY.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary,indent=2),flush=True)
if __name__=='__main__':main()
