"""Source-only test of whether the already-trained expanded CT/MR C helps MR.

Fit one fixed 512-tree development model, preserving the old source case split.
No independent-comparison predictions are accessed or generated by this audit.
"""
import json,os,time
import joblib,numpy as np
from sklearn.ensemble import ExtraTreesClassifier
from scripts.astra6_e05.run_e05 import P,PARAMS,group
from scripts.astra6_e01.e01_common import write_json,sha256_file

def main():
    old=P/'artifacts/astra6_e02_multiscale_vessel_signature_20260908T173916Z';expanded=P/'artifacts/astra6_e09_CT_expanded_location_20260909';audit=P/'artifacts/source_location_detector_box_audit_20260909';out=P/'artifacts/source_MR_CT_location_transfer_20260909';out.mkdir(exist_ok=True)
    config={'hypothesis':'Additional eligible CT anatomy examples may improve sparse MR location classes using the shared geometric classifier','change':'Only add eligible source CT rows to the development fit, identical512 ExtraTrees parameters and seed to existing source baseline','budget_minutes':15,'trees':512,'checkpoint_every_trees':64,'gate':'At least2 additional correct source detector-box lesions among31, with no reduction on the37 original source MR GT-box lesions','next_if_pass':'Test already-completed full E09 C on MR with all D/F/S decisions and weights frozen; no threshold sweep','no_MR40_or_CT5_access':True,'limitations':'Organizer-provided source silver vessel features; source detector has source training exposure'}
    write_json(out/'config.json',config)
    data=np.load(expanded/'features/train.npz');X,y=data['X'],data['y'];records=[json.loads(s) for s in (expanded/'features/train_records.jsonl').read_text().splitlines()]
    split=json.loads((P/'artifacts/astra6_e05_learned_location_splits_20260909/source_split.json').read_text());extra=json.loads((expanded/'source_split.json').read_text());exclude={group(c) for c in split['development_cases']+extra['source_development_cases']};tr=np.array([i for i,r in enumerate(records) if group(r['case_id']) not in exclude]);gt=np.array([i for i in split['development_rows'] if '_mr_' in records[i]['case_id']]);assert len(gt)==37 and not {group(records[i]['case_id']) for i in tr}&exclude
    write_json(out/'source_split.json',{'train_rows':tr.tolist(),'development_GT_rows':gt.tolist(),'excluded_case_groups':sorted(exclude),'feature_sha256':sha256_file(expanded/'features/train.npz')})
    vals,counts=np.unique(y[tr],return_counts=True);cw=dict(zip(vals,1/np.sqrt(counts)));weights=np.array([cw[v] for v in y[tr]]);weights/=weights.mean();path=out/'development.joblib';model=joblib.load(path) if path.exists() else ExtraTreesClassifier(n_estimators=64,warm_start=True,**PARAMS);start=len(model.estimators_)+64 if hasattr(model,'estimators_') else 64
    for n in range(start,513,64):
        t=time.monotonic();model.set_params(n_estimators=n);model.fit(X[tr],y[tr],sample_weight=weights);temp=path.with_suffix('.tmp');joblib.dump(model,temp,compress=3);os.replace(temp,path);print('SOURCE_MR_CT_TRANSFER',n,round(time.monotonic()-t,2),flush=True)
    baseline=joblib.load(P/'artifacts/astra6_e05_learned_location_splits_20260909/model/development_baseline.joblib');rows=json.loads((audit/'RESULT.json').read_text())['rows'];cases=sorted({r['case_id'] for r in rows});dx=np.concatenate([np.load(audit/f'{cid}.npz')['X'] for cid in cases]);dy=np.array([r['label'] for r in rows]);assert len(dx)==len(dy)==31
    before={'GT_correct':int((baseline.predict(X[gt])==y[gt]).sum()),'detector_correct':int((baseline.predict(dx)==dy).sum())};pred=model.predict(dx);after={'GT_correct':int((model.predict(X[gt])==y[gt]).sum()),'detector_correct':int((pred==dy).sum())};assert before['detector_correct']==25
    write_json(out/'RESULT.json',{'before':before,'after':after,'GT_n':37,'detector_n':31,'gate_passed':after['detector_correct']>=before['detector_correct']+2 and after['GT_correct']>=before['GT_correct'],'model_sha256':sha256_file(path),'full_model_already_trained':str(expanded/'model/classifier.joblib'),'parameters':PARAMS,'trees':512,'detector_predictions':pred.tolist(),'detector_labels':dy.tolist(),'no_MR40_or_CT5_access':True});print('SOURCE_MR_CT_TRANSFER_RESULT',before,after,flush=True)

if __name__=='__main__':main()
