"""New isolated E32 model candidate; never update or overwrite the retained r2 tree."""
import json,hashlib,shutil,time
from pathlib import Path
P=Path(__file__).resolve().parents[2];BASE=P/'submission_models_20260909';DEST=P/'submission_models_MRE32_CTE16_20260910_r3';RUN=P/'artifacts/astra6_e32_image_only_segmentation_20260910'
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(4*1024*1024),b''):h.update(b)
 return h.hexdigest()
def main():
 decision=json.loads((RUN/'DECISION.json').read_text());assert decision['decision']=='candidate_pending_raw_runtime_validation';lock=json.loads((RUN/'normalized/model/LOCKED.json').read_text());assert sha(RUN/'normalized/model/final_last.pt')==lock['model_sha256'];assert json.loads((RUN/'normalized/native_verification/PARITY.json').read_text())['passed'];assert not DEST.exists(),'Refusing to overwrite an existing candidate bundle'
 DEST.mkdir();(DEST/'STAGING.json').write_text(json.dumps({'timestamp':time.time(),'source_r2':str(BASE),'r2_untouched':True})+'\n')
 for name in ['models','source','configs']:shutil.copytree(BASE/name,DEST/name,ignore=shutil.ignore_patterns('__pycache__','*.pyc'))
 shutil.copyfile(BASE/'models/segmentation_MR.pt',DEST/'models/segmentation_MR_fallback.pt');shutil.copyfile(RUN/'normalized/model/final_last.pt',DEST/'models/segmentation_MR.pt');shutil.copytree(P/'scripts',DEST/'source/scripts',dirs_exist_ok=True,ignore=shutil.ignore_patterns('__pycache__','*.pyc'))
 entry=(BASE/'run_inference.py').read_text();entry=entry.replace("choices=['default','MR_E12_tradeoff']","choices=['default']");entry=entry.replace("cfg={k:v for k,v in modelcfg.items() if k.endswith('_threshold')}","cfg={k:v for k,v in modelcfg.items() if k.endswith('_threshold') or k.endswith('_architecture')}");entry=entry.replace(" if a.profile!='default':"," cfg['MR_fallback_segmentation']=str(ROOT/'models/segmentation_MR_fallback.pt')\n if a.profile!='default':");(DEST/'run_inference.py').write_text(entry)
 cfg=json.loads((DEST/'configs/models.json').read_text());cfg.update(system_version='MR_E32_image_candidate_48_CT_E16',MR_segmentation_architecture='E32_image_candidate_48');(DEST/'configs/models.json').write_text(json.dumps(cfg,indent=2)+'\n');reports=DEST/'reports';reports.mkdir()
 for source,name in [(RUN/'config.json','E32_PROTOCOL.json'),(RUN/'source_split.json','E32_SOURCE_SPLIT.json'),(RUN/'CASE_LINEAGE.json','E32_CASE_LINEAGE.json'),(RUN/'HYPOTHESIS_REVIEW_ADDENDUM.json','E32_HYPOTHESIS_REVIEW_ADDENDUM.json'),(RUN/'DECISION.json','E32_DEVELOPMENT_DECISION.json'),(RUN/'COMPARISONS.json','E32_PAIRED_COMPARISONS.json'),(RUN/'normalized/model/MODEL_CONTRACT.json','E32_MODEL_CONTRACT.json'),(P/'reports/PLANNING_PROVENANCE_CORRECTION_20260909.md','PLANNING_PROVENANCE_CORRECTION.md'),(P/'artifacts/current_official_20260909/E32_normalized/official.json','MR_OFFICIAL_SIX.json'),(P/'artifacts/current_official_20260909/CT_E16/official.json','CT_OFFICIAL_SIX_UNCHANGED.json')]:shutil.copyfile(source,reports/name)
 manifest={str(f.relative_to(DEST)):{'bytes':f.stat().st_size,'sha256':sha(f)} for f in sorted((DEST/'models').rglob('*')) if f.is_file()};(DEST/'MODEL_MANIFEST.json').write_text(json.dumps(manifest,indent=2)+'\n');source_manifest={str(f.relative_to(DEST)):sha(f) for f in sorted((DEST/'source').rglob('*')) if f.is_file()};(DEST/'SOURCE_MANIFEST.json').write_text(json.dumps(source_manifest,indent=2)+'\n')
 baseline=json.loads((BASE/'MODEL_MANIFEST.json').read_text());unchanged=[k for k in baseline if k!='models/segmentation_MR.pt'];assert all(manifest[k]==baseline[k] for k in unchanged);(DEST/'MODEL_CHANGE_PARITY.json').write_text(json.dumps({'all_previous_weights_except_MR_S_unchanged':True,'unchanged_files':unchanged,'new_MR_S_sha256':lock['model_sha256'],'fallback_S17_sha256':manifest['models/segmentation_MR_fallback.pt']['sha256'],'r2_unchanged':True},indent=2)+'\n');(DEST/'BUNDLE_STATUS.json').write_text(json.dumps({'status':'development_passed_raw_runtime_pending','T4_validated':False,'hidden_competition_submission':False,'container_build':'user-managed','source_planning_exposure':'Legacy D still has known supervised MR40/CT5 planning exposure; E33 source-only D is a separate experiment, not included.','MR40_evidence':'repeated development, not independent hidden test'},indent=2)+'\n')
 (DEST/'README.md').write_text('''# TopAneu Task 2：MR E32 / CT E16 模型候選\n\nMR 使用正式完成的 E32 影像與候選提示分割器；C02、F14、detector、TA36 及 CT E16 模型保留。這不是容器；容器由使用者建置。\n\n執行：\n\n```bash\npython run_inference.py --image /path/image.nii.gz --modality MR --output /path/prediction.nii.gz --work /path/new_work_dir --gpu 0 --detector-python /path/nndet/python --refinement-python /path/nnunet/python\n```\n\nCT 使用 `--modality CT`。`--work` 必須是不存在的新目錄。輸出為原始影像幾何的 uint8 NIfTI，背景0、位置標籤1–52。推論不讀取 GT。E32 的第二個卷積輸入通道必須由指定 Model.forward 清零，不能因權重形狀相同而換用 E31 Model。預測血管仍供 C02 使用。\n\n目前狀態以 BUNDLE_STATUS.json 為準。官方六指標、病例切分、權重/程式雜湊及已知 planning 暴露限制見 reports 與 manifests。MR40 是反覆研發使用的內部集合，不能宣稱獨立泛化；沒有保證競賽排名，也尚未完成實際 T4/隱藏競賽提交驗證。原 r2 完整保留。\n''');print('E32 CANDIDATE ASSEMBLED',DEST,len(manifest),len(source_manifest),flush=True)
if __name__=='__main__':main()
